# Syntax highlighting
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               WELTSTARS
tagline:             may the CI be with you
url:                 https://markusvogt.github.io/ws/
baseurl:             /ws/

# Styleguide Settings
sg_styles: styleguide/style.css

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          src/scss
  style:            :compressed